// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: net.gifdex.moderation.createReport
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic,
    Default
)]
#[serde(rename_all = "camelCase")]
pub struct CreateReport<'a> {
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub reason: std::option::Option<jacquard_common::CowStr<'a>>,
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub reason_category: std::option::Option<jacquard_common::CowStr<'a>>,
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub subject: std::option::Option<jacquard_common::types::string::AtUri<'a>>,
}

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic,
    Default
)]
#[serde(rename_all = "camelCase")]
pub struct CreateReportOutput<'a> {}
#[jacquard_derive::open_union]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic,
    jacquard_derive::IntoStatic
)]
#[serde(tag = "error", content = "message")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum CreateReportError<'a> {
    /// The caller is not authenticated.
    #[serde(rename = "AuthenticationRequired")]
    AuthenticationRequired(std::option::Option<jacquard_common::CowStr<'a>>),
    /// The resolved subject does not exist or has not been indexed yet.
    #[serde(rename = "SubjectNotFound")]
    SubjectNotFound(std::option::Option<jacquard_common::CowStr<'a>>),
}

impl std::fmt::Display for CreateReportError<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::AuthenticationRequired(msg) => {
                write!(f, "AuthenticationRequired")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::SubjectNotFound(msg) => {
                write!(f, "SubjectNotFound")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Unknown(err) => write!(f, "Unknown error: {:?}", err),
        }
    }
}

/// Response type for
///net.gifdex.moderation.createReport
pub struct CreateReportResponse;
impl jacquard_common::xrpc::XrpcResp for CreateReportResponse {
    const NSID: &'static str = "net.gifdex.moderation.createReport";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = CreateReportOutput<'de>;
    type Err<'de> = CreateReportError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for CreateReport<'a> {
    const NSID: &'static str = "net.gifdex.moderation.createReport";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = CreateReportResponse;
}

/// Endpoint type for
///net.gifdex.moderation.createReport
pub struct CreateReportRequest;
impl jacquard_common::xrpc::XrpcEndpoint for CreateReportRequest {
    const PATH: &'static str = "/xrpc/net.gifdex.moderation.createReport";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<'de> = CreateReport<'de>;
    type Response = CreateReportResponse;
}