// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: net.gifdex.feed.getPostNotReal
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct GetPostNotReal {
    pub created_at: jacquard_common::types::string::Datetime,
    ///(min: 1)
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    pub duration_minutes: std::option::Option<i64>,
    pub status: i64,
}

pub mod get_post_not_real_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type CreatedAt;
        type Status;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type CreatedAt = Unset;
        type Status = Unset;
    }
    ///State transition - sets the `created_at` field to Set
    pub struct SetCreatedAt<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetCreatedAt<S> {}
    impl<S: State> State for SetCreatedAt<S> {
        type CreatedAt = Set<members::created_at>;
        type Status = S::Status;
    }
    ///State transition - sets the `status` field to Set
    pub struct SetStatus<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetStatus<S> {}
    impl<S: State> State for SetStatus<S> {
        type CreatedAt = S::CreatedAt;
        type Status = Set<members::status>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `created_at` field
        pub struct created_at(());
        ///Marker type for the `status` field
        pub struct status(());
    }
}

/// Builder for constructing an instance of this type
pub struct GetPostNotRealBuilder<S: get_post_not_real_state::State> {
    _phantom_state: ::core::marker::PhantomData<fn() -> S>,
    __unsafe_private_named: (
        ::core::option::Option<jacquard_common::types::string::Datetime>,
        ::core::option::Option<i64>,
        ::core::option::Option<i64>,
    ),
}

impl GetPostNotReal {
    /// Create a new builder for this type
    pub fn new() -> GetPostNotRealBuilder<get_post_not_real_state::Empty> {
        GetPostNotRealBuilder::new()
    }
}

impl GetPostNotRealBuilder<get_post_not_real_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        GetPostNotRealBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: (None, None, None),
        }
    }
}

impl<S> GetPostNotRealBuilder<S>
where
    S: get_post_not_real_state::State,
    S::CreatedAt: get_post_not_real_state::IsUnset,
{
    /// Set the `createdAt` field (required)
    pub fn created_at(
        mut self,
        value: impl Into<jacquard_common::types::string::Datetime>,
    ) -> GetPostNotRealBuilder<get_post_not_real_state::SetCreatedAt<S>> {
        self.__unsafe_private_named.0 = ::core::option::Option::Some(value.into());
        GetPostNotRealBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
        }
    }
}

impl<S: get_post_not_real_state::State> GetPostNotRealBuilder<S> {
    /// Set the `durationMinutes` field (optional)
    pub fn duration_minutes(mut self, value: impl Into<Option<i64>>) -> Self {
        self.__unsafe_private_named.1 = value.into();
        self
    }
    /// Set the `durationMinutes` field to an Option value (optional)
    pub fn maybe_duration_minutes(mut self, value: Option<i64>) -> Self {
        self.__unsafe_private_named.1 = value;
        self
    }
}

impl<S> GetPostNotRealBuilder<S>
where
    S: get_post_not_real_state::State,
    S::Status: get_post_not_real_state::IsUnset,
{
    /// Set the `status` field (required)
    pub fn status(
        mut self,
        value: impl Into<i64>,
    ) -> GetPostNotRealBuilder<get_post_not_real_state::SetStatus<S>> {
        self.__unsafe_private_named.2 = ::core::option::Option::Some(value.into());
        GetPostNotRealBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
        }
    }
}

impl<S> GetPostNotRealBuilder<S>
where
    S: get_post_not_real_state::State,
    S::CreatedAt: get_post_not_real_state::IsSet,
    S::Status: get_post_not_real_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> GetPostNotReal {
        GetPostNotReal {
            created_at: self.__unsafe_private_named.0.unwrap(),
            duration_minutes: self.__unsafe_private_named.1,
            status: self.__unsafe_private_named.2.unwrap(),
        }
    }
}

/// Response type for
///net.gifdex.feed.getPostNotReal
pub struct GetPostNotRealResponse;
impl jacquard_common::xrpc::XrpcResp for GetPostNotRealResponse {
    const NSID: &'static str = "net.gifdex.feed.getPostNotReal";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = ();
    type Err<'de> = jacquard_common::xrpc::GenericError<'de>;
}

impl jacquard_common::xrpc::XrpcRequest for GetPostNotReal {
    const NSID: &'static str = "net.gifdex.feed.getPostNotReal";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetPostNotRealResponse;
}

/// Endpoint type for
///net.gifdex.feed.getPostNotReal
pub struct GetPostNotRealRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetPostNotRealRequest {
    const PATH: &'static str = "/xrpc/net.gifdex.feed.getPostNotReal";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<'de> = GetPostNotReal;
    type Response = GetPostNotRealResponse;
}